export const instructorsData = {
    'maria': {
        name: 'María',
        style: 'Hatha Yoga & Yin Yoga',
        style_en: 'Hatha Yoga & Yin Yoga',
        image: 'assets/instructoras/Maria.jpeg',
        bio: 'Mi práctica de yoga se fundamenta en más de 10 años de experiencia y en una convicción clara: el bienestar y el descanso son derechos fundamentales, no privilegios exclusivos de unos pocos. Mi formación combina el Yoga tradicional (Hata, restaurativo) con enfoques contemporáneos basados en la ciencia, como la psicoendocrinología y la atención informada en trauma. Además, mis nueve años asistiendo en consultas de traumatología me dieron una comprensión profunda y real de la anatomía humana, permitiéndome ver más allá de las posturas estéticas para enfocarme en la funcionalidad, la movilidad articular y la salud del sistema nervioso. No busco que mis alumnos realicen acrobacias, sino que fortalezcan su cuerpo para la vida diaria y encuentren un espacio seguro para habitarse a sí mismos.<br><br>A lo largo de mi carrera, he tenido el privilegio de acompañar a una diversidad inmensa de personas, derribando la idea de que el yoga requiere un tipo de cuerpo, edad o estatus social específico. Actualmente, guío a alumnas que van desde los 18 hasta los 85 años, adaptando la práctica a cada necesidad. Mi labor docente me ha llevado desde impartir clases particulares y sesiones para personal de hotelería y servicio, hasta trabajar dentro de centros penitenciarios (femeninos y masculinos) y apoyar a madres autónomas. Entiendo la vulnerabilidad humana y la importancia de crear espacios donde no exista el juicio, sino la aceptación.<br><br>En mis clases, ofrezco una guía honesta y participativa. Trabajamos con respiración suave para regular el sistema nervioso y movimientos conscientes que respetan la biomecánica individual. Mi objetivo no es prometer soluciones mágicas, sino facilitar herramientas corporales y mentales que te permitan transitar tus propios procesos, gestionar el dolor o la ansiedad, y reclamar tu derecho a sentirte bien, descansar y vivir sin dolor, independientemente del contexto que te rodee.',
        bio_en: 'My yoga practice is grounded in over 10 years of experience and a clear conviction: well-being and rest are fundamental rights, not exclusive privileges. My background combines traditional Yoga (Hatha, restorative) with contemporary science-based approaches like psychoendocrinology and trauma-informed care. Additionally, my nine years assisting in trauma consultations gave me a deep and real understanding of human anatomy, allowing me to look beyond aesthetic postures to focus on functionality, joint mobility, and nervous system health. I don\'t seek for my students to perform acrobatics, but to strengthen their bodies for daily life and find a safe space to inhabit themselves.<br><br>Throughout my career, I have had the privilege of accompanying an immense diversity of people, breaking down the idea that yoga requires a specific body type, age, or social status. Currently, I guide students ranging from 18 to 85 years old, adapting the practice to each need. My teaching work has taken me from giving private classes and sessions for hotel and service staff, to working within prisons (female and male) and supporting single mothers. I understand human vulnerability and the importance of creating spaces where there is no judgment, only acceptance.<br><br>In my classes, I offer honest and participatory guidance. We work with soft breathing to regulate the nervous system and conscious movements that respect individual biomechanics. My goal is not to promise magic solutions, but to facilitate bodily and mental tools that allow you to navigate your own processes, manage pain or anxiety, and reclaim your right to feel good, rest, and live without pain, regardless of the context surrounding you.',
        quote: 'Que nuestra practica y comunidad se conviertan en<br>Un espacio abierto. Un refugio amoroso.<br>Un lugar para mover el cuerpo, respirar profundo, y hacer comunidad.<br>Una práctica compartida, para no seguir cargando solas lo que duele en común.',
        quote_en: 'May our practice and community become<br>An open space. A loving shelter.<br>A place to move the body, breathe deep, and build community.<br>A shared practice, so we don\'t keep carrying alone what hurts in common.',
        classDesc: 'Un espacio seguro e inclusivo donde unimos yoga y ciencia para regular tu sistema nervioso y fortalecer tu cuerpo real, adaptándonos a tu edad y condición. Busco ofrecerte herramientas funcionales de movilidad, fortaleza y respiración para gestionar el estrés, aliviar tensiones y vivir sin dolor.',
        classDesc_en: 'A safe and inclusive space where we unite yoga and science to regulate your nervous system and strengthen your real body, adapting to your age and condition. I seek to offer functional tools for mobility, strength, and breathing to manage stress, relieve tension, and live without pain.',
        phone: '529513464383'
    },
    'alosja': {
        name: 'Alosja',
        style: 'Alineamiento Restaurativo',
        style_en: 'Restorative Alignment',
        image: 'assets/instructoras/Alosja.jpg',
        bio: 'Con más de 10 años de práctica, me he dedicado a estudiar las raíces del yoga para compartirlas de manera accesible. Mi enfoque es la alineación y la permanencia en las posturas para cultivar paciencia y observación profunda.',
        bio_en: 'With over 10 years of practice, I have dedicated myself to studying the roots of yoga to share them in an accessible way. My focus is on alignment and holding postures to cultivate patience and deep observation.',
        quote: 'La comunidad es el cimiento firme sobre el cual construimos nuestra práctica personal; es el recordatorio de que somos espejos los unos de los otros.',
        quote_en: 'Community is the firm foundation upon which we build our personal practice; it is the reminder that we are mirrors of each other.',
        classDesc: 'Una práctica pausada y estructurada, enfocada en la alineación correcta, el uso de props para adaptar la postura al cuerpo y la integración de pranayama (respiración).',
        classDesc_en: 'A paced and structured practice, focused on correct alignment, the use of props to adapt the posture to the body, and the integration of pranayama (breathing).',
        phone: '529513464383'
    },
    'phan': {
        name: 'Phan',
        style: 'Vinyasa somática',
        style_en: 'Somatic Vinyasa',
        image: null,
        bio: 'Descubrí el yoga restaurativo como una herramienta de sanación profunda para el sistema nervioso. Mi misión es crear espacios de descanso radical en un mundo que glorifica la prisa constante.',
        bio_en: 'I discovered restorative yoga as a tool for deep healing of the nervous system. My mission is to create spaces of radical rest in a world that glorifies constant rush.',
        quote: 'En el descanso compartido encontramos la fuerza para sostenernos mutuamente. Sostener comunidad es permitirnos ser vulnerables y descansar juntos.',
        quote_en: 'In shared rest we find the strength to hold each other. Holding community is allowing ourselves to be vulnerable and rest together.',
        classDesc: 'Posturas sostenidas por largos periodos con el apoyo total de props (cojines, mantas, bloques) para inducir una relajación profunda y restaurar la energía vital.',
        classDesc_en: 'Postures held for long periods with full support of props (cushions, blankets, blocks) to induce deep relaxation and restore vital energy.',
        phone: '529513464383'
    },
    'karina': {
        name: 'Karina',
        style: 'Hatha Yoga & Hatha Suave',
        style_en: 'Hatha Yoga & Gentle Hatha',
        image: 'assets/instructoras/Karina.jpeg',
        bio: 'Me alivia saber la teoría de que soy un amplio espectro de posibles roles y comportamientos y no solamente una instructora.<br><br>Pienso que las personas llegan a ciertos lugares por curiosidad o por algún interés en particular pero muchas veces se encuentran con cosas más sutiles... Mis primeras clases de yoga fueron para apoyar a un amigo que estaba impartiendo sus prácticas, él dejó de dar clases.<br><br>Entre el ajetreo de ocupaciones, sentí que debía continuar por mi bien. Entonces continué tomando clases y encontré una fortuna, haber llegado a instructores que, más allá de la postura me ayudaron a interiorizar, fue un ¡bum! para mí, con el tiempo me di cuenta que más que encontrar un espacio físico para asistir a tomar clases, era el pretexto perfecto para entrar en mi espacio interior, encontrando un refugio.<br><br>Intento mantener ese toque con quienes comparten su presencia en mis clases.<br>Esto es experimental y el yoga es solo una herramienta más entre muchas otras donde puedes encontrar tu refugio.',
        bio_en: 'It relieves me to know the theory that I am a wide spectrum of possible roles and behaviors and not just an instructor.<br><br>I think people come to certain places out of curiosity or some particular interest but often find more subtle things... My first yoga classes were to support a friend who was teaching his practices, be stopped teaching.<br><br>Between the hustle of occupations, I felt I had to continue for my own good. So I continued taking classes and found a fortune, having reached instructors who, beyond the posture helped me internalize, it was a boom! for me, with time I realized that more than finding a physical space to attend classes, it was the perfect pretext to enter my inner space, finding a refuge.<br><br>I try to keep that touch with those who share their presence in my classes.<br>This is experimental and yoga is just one more tool among many others where you can find your refuge.',
        quote: 'Aprecio la simpleza de las cosas, los lugares naturales, y la comodidad de una buena plática.',
        quote_en: 'I appreciate the simplicity of things, natural places, and the comfort of a good conversation.',
        classDesc: 'Mis clases están pensadas para todas las personas, en especial para principiantes. Hatha yoga es una de las formas más accesibles. Trabajamos con Respiración, Mente y Espíritu, sin dogmas, solo un espacio para conectar con lo sagrado de lo simple.<br><br>Son prácticas que nos invitan a habitar el cuerpo, a suavizar la mente y a despertar el corazón.<br><br>Enseño yoga desde el año 2011. Estudié con diferentes maestros y diferentes estilos lo que me permite hacer de mis sesiones un enfoque libre y adaptativo. Muchas veces las posturas nos pueden dar la oportunidad de autoconocernos y sanarnos (florecer).<br><br>Son ideales para principiantes y personas que ya practican y que prefieren un estilo que no se trata de formas perfectas, sino de presencia honesta. De permitirnos sentir, respirar, movernos… y florecer.',
        classDesc_en: 'My classes are designed for everyone, especially for beginners. Hatha yoga is one of the most accessible forms. We work with Breath, Mind and Spirit, without dogmas, just a space to connect with the sacred of the simple.<br><br>These are practices that invite us to inhabit the body, soften the mind and awaken the heart.<br><br>I have been teaching yoga since 2011. I studied with different teachers and different styles which allows me to make my sessions a free and adaptive approach. Often postures can give us the opportunity to know ourselves and heal (bloom).<br><br>They are ideal for beginners and people who already practice and prefer a style that is not about perfect forms, but honest presence. To allow us to feel, breathe, move... and bloom.',
        phone: '529513464383'
    }
};
